version: '3.8'

services:
  # Servicio para la aplicación en desarrollo
  easy-reserve-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: spring-easy-reserve-dev
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - spring-network-dev
    depends_on:
      - mysql_dev
    profiles:
      - dev  # Este servicio solo se levantará cuando se especifique el perfil 'dev'

  # Servicio para la base de datos en desarrollo
  mysql_dev:
    image: mysql:latest
    container_name: mysql_database_dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: easyreserve_dev_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - spring-network-dev
    profiles:
      - dev  # Este servicio solo se levantará cuando se especifique el perfil 'dev'

  # Servicio para la aplicación en producción
  easy-reserve-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: spring-easy-reserve-prod
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - spring-network-prod
    depends_on:
      - mysql_prod
    profiles:
      - prod  # Este servicio solo se levantará cuando se especifique el perfil 'prod'

  # Servicio para la base de datos en producción
  mysql_prod:
    image: mysql:latest
    container_name: mysql_database_prod
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: easyreserve_prod_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql
    networks:
      - spring-network-prod
    profiles:
      - prod  # Este servicio solo se levantará cuando se especifique el perfil 'prod'

  # Servicio para la aplicación en pruebas
  easy-reserve-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: spring-easy-reserve-test
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: test
    networks:
      - spring-network-test
    depends_on:
      - mysql_test
    profiles:
      - test  # Este servicio solo se levantará cuando se especifique el perfil 'test'

  # Servicio para la base de datos en pruebas
  mysql_test:
    image: mysql:latest
    container_name: mysql_database_test
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: easyreserve_test_db
    ports:
      - "3309:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
    networks:
      - spring-network-test
    profiles:
      - test  # Este servicio solo se levantará cuando se especifique el perfil 'test'

networks:
  spring-network-dev:
    driver: bridge
  spring-network-prod:
    driver: bridge
  spring-network-test:
    driver: bridge

volumes:
  mysql_prod_data:
  mysql_dev_data:
  mysql_test_data:
