services:
  mysql_prod:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: easyreserve_prod_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql

  mysql_dev:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: easyreserve_dev_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql

  mysql_test:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: easyreserve_test_db
    ports:
      - "3309:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql




volumes:
  mysql_prod_data:
  mysql_dev_data:
  mysql_test_data:
