services:
  mysql_prod:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: easyreserve_prod_db
    ports:
      - "3307:3306"

  mysql_dev:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: easyreserve_dev_db
    ports:
      - "3308:3306"

  mysql_test:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: easyreserve_test_db
    ports:
      - "3309:3306"